# Generated by Django 3.2.18 on 2023-03-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ItemImg',
            new_name='ProductImg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createDate',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='productimg',
            old_name='itemId',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='createDate',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createDate',
            new_name='create_at',
        ),
    ]
