# Generated by Django 3.2.18 on 2023-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20230318_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='createDate',
            new_name='create_at',
        ),
    ]
